export { default as SearchIcon } from './Search/Search'
export { default as BookIcon } from './Book/Book'
export { default as DolarIcon } from './Dolar/Dolar'
export { default as ClockIcon } from './Clock/Clock'
export { default as HeartIcon } from './Heart/Heart'
